version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak-db
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HOSTNAME: localhost
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_REALM_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_REALM_ADMIN_PASSWORD}
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/keycloak-config.json
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    command: start-dev --import-realm
    volumes:
      - ./keycloak-config.json:/opt/keycloak/data/import/keycloak-config.json

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: app
#    environment:
#      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
#      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
#      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
#      OAUTH2_ISSUER_URI: ${OAUTH2_ISSUER_URI}
#      OAUTH2_JWK_SET_URI: ${OAUTH2_JWK_SET_URI}
#      KEYCLOAK_AUTH_SERVER_URL: ${KEYCLOAK_AUTH_SERVER_URL}
#      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
#      KEYCLOAK_RESOURCE: ${KEYCLOAK_RESOURCE}
#      KEYCLOAK_SECRET: ${KEYCLOAK_SECRET}
#      KEYCLOAK_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
#      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
#      - keycloak

volumes:
  postgres_data:
